#!/bin/sh
set -e
git describe --tags &> /dev/null || { echo "0.1.0"; exit 0; }
SEMVER=$(git --no-pager tag -l | grep -E "\d+\.\d+\.\d+" | tail -1)
MAJOR=$(echo "$SEMVER" | grep -oE "\d+" | head -1)
MINOR=$(echo "$SEMVER" | grep -oE "\d+" | head -2 | tail -1)
PATCH=$(echo "$SEMVER" | grep -oE "\d+" | tail -1)
GIT_LOG=$(git --no-pager log $SEMVER..HEAD --oneline)
echo $GIT_LOG | grep -qv "BREAK" || { echo "$((MAJOR+1)).0.0"; exit 0; }
echo $GIT_LOG | grep -qv "FEAT" || { echo "$MAJOR.$((MINOR+1)).0"; exit 0; }
echo $GIT_LOG | grep -qvE "FIX|PERF|CODE|TEST|DEPS|CHORE|DOCS" || { echo "$MAJOR.$MINOR.$((PATCH+1))"; exit 0; }
echo "$MAJOR.$MINOR.$PATCH"
